public class Test1{
    public void sample(){
    
    }
public string username{get;set;}
public string password{get;set;}
public string result{get;set;}

    public Test1(){
    
    }
    
    public void validateCredentials() {
        if(username=='XXX' && password=='YYY') {
            result='login successfully';
        }
        else {
        
            result='login failed';
        }
            
    }
        }